//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRR_AIEntities2 : DbContext
    {
        public DBRR_AIEntities2()
            : base("name=DBRR_AIEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SN_M_logs> SN_M_logs { get; set; }
        public virtual DbSet<SN_M_musteriListesi> SN_M_musteriListesi { get; set; }
        public virtual DbSet<SN_M_urunListesi> SN_M_urunListesi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SN_M_Menu> SN_M_Menu { get; set; }
        public virtual DbSet<SN_M_SubMenu> SN_M_SubMenu { get; set; }
        public virtual DbSet<SN_M_calisanListesi> SN_M_calisanListesi { get; set; }
        public virtual DbSet<SN_M_kategoriListesi> SN_M_kategoriListesi { get; set; }
        public virtual DbSet<SN_M_urunFiyatListesi> SN_M_urunFiyatListesi { get; set; }
        public virtual DbSet<SN_M_islemTipiListesi> SN_M_islemTipiListesi { get; set; }
        public virtual DbSet<SN_M_faturaListesi> SN_M_faturaListesi { get; set; }
        public virtual DbSet<SN_M_islemler> SN_M_islemler { get; set; }
        public virtual DbSet<SN_M_satisListesi> SN_M_satisListesi { get; set; }
    }
}
