//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_SubMenu
    {
        public int ID { get; set; }
        public int menuID { get; set; }
        public string subAdi { get; set; }
        public string subAction { get; set; }
        public int subSirasi { get; set; }
    
        public virtual SN_M_Menu SN_M_Menu { get; set; }
    }
}
