//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_satisListesi
    {
        public int satisID { get; set; }
        public int calisanID { get; set; }
        public System.DateTime satisTarihi { get; set; }
        public int satisFiyatiID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public int satilanUrunID { get; set; }
        public int adet { get; set; }
    }
}
