//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_urunFiyatListesi
    {
        public int ID { get; set; }
        public int urunID { get; set; }
        public decimal urunFiyati { get; set; }
        public System.DateTime fiyatTarihi { get; set; }
        public bool isActive { get; set; }
    
        public virtual SN_M_urunListesi SN_M_urunListesi { get; set; }
    }
}
