//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_logs
    {
        public int logID { get; set; }
        public string tabloAdı { get; set; }
        public string logType { get; set; }
        public string logDesc { get; set; }
        public System.DateTime logTime { get; set; }
        public string oldValues { get; set; }
        public string newValues { get; set; }
    }
}
