//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_calisanListesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SN_M_calisanListesi()
        {
            this.SN_M_islemler = new HashSet<SN_M_islemler>();
        }
    
        public int calisanID { get; set; }
        public string calisanAdi { get; set; }
        public string calisanSoyadi { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SN_M_islemler> SN_M_islemler { get; set; }
    }
}
