//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_MarketUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_M_urunListesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SN_M_urunListesi()
        {
            this.SN_M_urunFiyatListesi = new HashSet<SN_M_urunFiyatListesi>();
            this.SN_M_islemler = new HashSet<SN_M_islemler>();
        }
    
        public int urunBarkod { get; set; }
        public string urunAdi { get; set; }
        public int urunKategoriID { get; set; }
        public string birim { get; set; }
        public string urunResimURL { get; set; }
        public bool isActive { get; set; }
    
        public virtual SN_M_kategoriListesi SN_M_kategoriListesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SN_M_urunFiyatListesi> SN_M_urunFiyatListesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SN_M_islemler> SN_M_islemler { get; set; }
    }
}
